name: tune_tangler
packages:
  - . # Jeśli masz monorepo, dodaj inne ścieżki do pakietów
scripts:
  build-version-increment:
    run: dart scripts/version_update.dart --build
  apk-version-increment:
    run: dart scripts/version_update.dart --patch
  build-apk:
    run: melos run build-version-increment && flutter build apk
  install-apk:
#    run: flutter install
    run: adb install -r build/app/outputs/flutter-apk/app-release.apk
  apk:
    run: melos run build-apk && melos run install-apk
  build-debug-apk:
    run: melos run build-version-increment && flutter build apk --debug
  install-debug-apk:
#    run: flutter install --debug
    run: adb install -r build/app/outputs/flutter-apk/app-debug.apk
  debug-apk:
    run: melos run build-debug-apk && melos run install-debug-apk
#  build-ios:
#    run: melos run update-version && flutter build ios
