name: 'Setup Flutter'
description: 'Setup Flutter environment for TuneTangler'
inputs:
  flutter_version:
    description: 'Flutter version to use'
    required: false
    default: '3.35.1'
  flutter_channel:
    description: 'Flutter channel to use'
    required: false
    default: 'stable'
  with_dependencies:
    description: 'Get Flutter dependencies'
    required: false
    default: 'true'
  with_localization:
    description: 'Generate localization files'
    required: false
    default: 'true'


runs:
  using: 'composite'
  steps:
    - name: "🔧 Checkout code"
      uses: actions/checkout@v4
      
    - name: "🔧 Setup Flutter"
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter_version }}
        channel: ${{ inputs.flutter_channel }}
        cache-key: flutter-${{ runner.os }}-${{ inputs.flutter_version }}-${{ inputs.flutter_channel }}
        cache-version: ${{ inputs.flutter_version }}
        
    - name: "📦 Get dependencies"
      if: ${{ inputs.with_dependencies == 'true' }}
      shell: bash
      run: flutter pub get
      
    - name: "🌐 Generate localization files"
      if: ${{ inputs.with_localization == 'true' }}
      shell: bash
      run: flutter gen-l10n

    # Cache Flutter dependencies
    - name: "📦 Cache Flutter dependencies"
      uses: actions/cache@v4
      with:
        path: |
          ~/.pub-cache
          .dart_tool
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: flutter-${{ runner.os }}-${{ inputs.flutter_version }}-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          flutter-${{ runner.os }}-${{ inputs.flutter_version }}-
          flutter-${{ runner.os }}-