name: Test Workflow

on:
  pull_request:
    branches: [ main ]

# Version variables for dependencies
env:
  FLUTTER_CHANNEL: 'stable'
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'zulu'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: "🔧 Checkout code"
        uses: actions/checkout@v4

      - name: "📲 Setup Flutter"
        uses: ./.github/actions/setup-flutter
        with:
          flutter_channel: ${{ env.FLUTTER_CHANNEL }}
          with_dependencies: true
          with_localization: false

      - name: "🧪 Run tests"
        uses: ./.github/actions/flutter-test
