name: Test Workflow

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    # Version variables for dependencies
    env:
      FLUTTER_VERSION: '3.35.1'
      FLUTTER_CHANNEL: 'stable'
      JAVA_VERSION: '17'
      JAVA_DISTRIBUTION: 'zulu'
    
    steps:
      - name: "🔧 Checkout code"
        uses: actions/checkout@v4
        
      - name: "🔧 Setup Flutter"
        uses: ./.github/actions/setup-flutter
        with:
          flutter_version: ${{ env.FLUTTER_VERSION }}
          flutter_channel: ${{ env.FLUTTER_CHANNEL }}
          with_dependencies: true
          with_localization: false
          with_test: true
